mysite1/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name='common'

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] 

mysite1/config/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('todolist/', include('todolist.urls')),

    path('common/', include('common.urls')),

    path('', views.index, name='index'),
]

mysite1/todolist/urls.py
from django.urls import path

from . import views

app_name='todolist'

urlpatterns=[
    path('', views.index, name='index'),
    path('<int:diary_id>/', views.detail, name='detail'),
    path('comment/create/<int:diary_id>/', views.comment_create, name='comment_create'),
    path('diary/create/', views.diary_create, name="diary_create")
]

mysite1/common/models.py
from django.db import models

# Create your models here.

mysite1/todolist/models.py
from django.db import models


class Diary(models.Model):
    subject=models.CharField(max_length=100)
    content=models.TextField()
    create_date=models.DateTimeField()

    def __str__(self):
        return self.subject

class Comment(models.Model):
    diary=models.ForeignKey(Diary, on_delete=models.CASCADE)
    content=models.TextField()
    create_date=models.DateTimeField()

mysite1/todolist/forms.py
from django import forms
from todolist.models import Diary, Comment

class DiaryForm(forms.ModelForm):
    class Meta:
        model=Diary
        fields=['subject', 'content']

        labels={
            'subject':'제목',
            'content':'내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']
        labels={
            'content':'답변내용',
        }

mysite1/common/views.py
from django.shortcuts import render

# Create your views here.

mysite1/todolist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Diary, Comment
from django.utils import timezone
from .forms import DiaryForm, CommentForm
from django.core.paginator import Paginator

# Create your views here.


def index(request):

   page=request.GET.get('page','1')

   diary_list = Diary.objects.order_by('-create_date')

   paginator=Paginator(diary_list, 10)
   page_obj=paginator.get_page(page)

   context = {'diary_list': page_obj}
   return render(request, 'todolist/diary_list.html', context)


def detail(request, diary_id):
    diary = get_object_or_404(Diary, pk=diary_id)
    context = {'diary': diary}
    return render(request, 'todolist/diary_detail.html', context)


def comment_create(request, diary_id):
    diary = get_object_or_404(Diary, pk=diary_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.diary = diary
            comment.save()
            return redirect('todolist:detail', diary_id=diary.id)
    else:
        form = CommentForm()

    context = {'diary': diary, 'form': form}
    return render(request, 'todolist/diary_detail.html', context)

    diary.comment_set.create(content=request.POST.get(
        'content'), create_date=timezone.now())
    return redirect('todolist:detail', diary_id=diary.id)


def diary_create(request):

    if request.method == 'POST':
        form = DiaryForm(request.POST)
        if form.is_valid():
            diary = form.save(commit=False)
            diary.create_date = timezone.now()
            diary.save()
            return redirect('todolist:index')
    else:
        form = DiaryForm()

    context = {'form': form}
    return render(request, 'todolist/diary_form.html', context)

mysite1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My To Do List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}">
</head>
<body>

    {% include "navbar.html" %}
    
    {% block content %}
    {% endblock %}

    <script src="{% static 'jquery.min.js' %}"></script>

    <script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

mysite1/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username"
            value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
            value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

mysite1/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

mysite1/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'todolist:index' %}">To do List</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

mysite1/templates/todolist/diary_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ diary.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ diary.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ diary.create_date }}
                </div>
            </div>
        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{ diary.comment_set.count }}개의 코멘트가 있습니다.</h5>
    {% for comment in diary.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ comment.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'todolist:comment_create' diary.id %}" method="post" class="my-3">
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors}}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

mysite1/templates/todolist/diary_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">to do list 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
            value="{{ form.subject.value|default_if_none:'' }}">
        </div>

        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

mysite1/templates/todolist/diary_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if diary_list %}
            {% for diary in diary_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'todolist:detail' diary.id %}">{{ diary.subject }}</a>
                    {% if diary.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ diary.comment_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ diary.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">할 일이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <ul class="pagination justify-content-center">
        {% if diary_list.has_previous %}
        <li class="page item">
            <a class="page-link" href="?page{{ diary_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        {% for page_number in diary_list.paginator.page_range %}

        {% if page_number >= diary_list.number|add:-5 and page_number <= diary_list.number|add:5 %} 
            {% if page_number == diary_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}

        {% endif %}

        {% endfor %}

        {% if diary_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ diary_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

    <a href="{% url 'todolist:diary_create' %}" class="btn btn-primary">to do list 작성</a>
</div>

{% endblock %}